name: build (forge)
on:
  release:
    types: [created]
jobs:
  build_1_20:
    if: "!startsWith(github.event.head_commit.message, '[skip]')"
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - name: pull from repo
        uses: actions/checkout@v3

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: granting exec perms to gradlew
        run: chmod +x ./gradlew

      - name: execute gradlew
        run: ./gradlew assemble -PmcVer="1.20.1"